/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

import java.awt.Color;

/**
 *
 * @author Luis
 */
public class Calculadora extends javax.swing.JFrame {
    
    private double n1;
    private double n2;
    private String operacion;

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
      
        initComponents();
        trns();
        this.getContentPane().setBackground(Color.black);
        jPanel1.setBackground(Color.black);

        this.setTitle("Calculadora");
        this.setLocationRelativeTo(null);
        
    }
   
    
    public void trns(){
      
        
        //raiz
        Raiz.setOpaque(false);
        Raiz.setContentAreaFilled(false);
        Raiz.setBorderPainted(false);
        
        //mas
        mas.setOpaque(false);
        mas.setContentAreaFilled(false);
        mas.setBorderPainted(false);
        //menos
        menos.setOpaque(false);
        menos.setContentAreaFilled(false);
        menos.setBorderPainted(false);
        //multiplicacion
        por.setOpaque(false);
        por.setContentAreaFilled(false);
        por.setBorderPainted(false);
        //division
        entre.setOpaque(false);
        entre.setContentAreaFilled(false);
        entre.setBorderPainted(false);
        //porcentaje
        porcentaje1.setOpaque(false);
        porcentaje1.setContentAreaFilled(false);
        porcentaje1.setBorderPainted(false);
        //borrart
        borrar.setOpaque(false);
        borrar.setContentAreaFilled(false);
        borrar.setBorderPainted(false);
        //borrar
        borrartodo.setOpaque(false);
        borrartodo.setContentAreaFilled(false);
        borrartodo.setBorderPainted(false);
        //1
        one.setOpaque(false);
        one.setContentAreaFilled(false);
        one.setBorderPainted(false);
        //2
        two.setOpaque(false);
        two.setContentAreaFilled(false);
        two.setBorderPainted(false);
        //3
        three.setOpaque(false);
        three.setContentAreaFilled(false);
        three.setBorderPainted(false);
        //4
        four.setOpaque(false);
        four.setContentAreaFilled(false);
        four.setBorderPainted(false);
         //5
        five.setOpaque(false);
        five.setContentAreaFilled(false);
        five.setBorderPainted(false);
        //6
        six.setOpaque(false);
        six.setContentAreaFilled(false);
        six.setBorderPainted(false);
        //7
        seven.setOpaque(false);
        seven.setContentAreaFilled(false);
        seven.setBorderPainted(false);
        //8
        eight.setOpaque(false);
        eight.setContentAreaFilled(false);
        eight.setBorderPainted(false);//6
        six.setOpaque(false);
        six.setContentAreaFilled(false);
        six.setBorderPainted(false);
        //7
        seven.setOpaque(false);
        seven.setContentAreaFilled(false);
        seven.setBorderPainted(false);
        //8
        eight.setOpaque(false);
        eight.setContentAreaFilled(false);
        eight.setBorderPainted(false);
        //9
        nine.setOpaque(false);
        nine.setContentAreaFilled(false);
        nine.setBorderPainted(false);
       //0
        zero.setOpaque(false);
        zero.setContentAreaFilled(false);
        zero.setBorderPainted(false);
        //.
        punto.setOpaque(false);
        punto.setContentAreaFilled(false);
        punto.setBorderPainted(false);
        //etrada
        entrada.setOpaque(false);
        entrada.setBorder(null);
        //igual
        igual.setOpaque(false);
        igual.setContentAreaFilled(false);
        igual.setBorderPainted(false);
        //jLabel1
       ;
        
        
        
        
    }
    public void entrada_datos(String texto){
        
        entrada.setText(entrada.getText()+ texto);
    }
    public void SELECIONARO(String operacion){
        
        n1= Double.parseDouble(entrada.getText());
        entrada.setText(" ");
        this.operacion= operacion;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jTextField1 = new javax.swing.JTextField();
        borrartodo = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        entre = new javax.swing.JButton();
        por = new javax.swing.JButton();
        menos = new javax.swing.JButton();
        Raiz = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        nine = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        five = new javax.swing.JButton();
        four = new javax.swing.JButton();
        two = new javax.swing.JButton();
        six = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        punto = new javax.swing.JButton();
        three = new javax.swing.JButton();
        one = new javax.swing.JButton();
        igual = new javax.swing.JButton();
        mas = new javax.swing.JButton();
        entrada = new javax.swing.JTextField();
        porcentaje1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        borrartodo.setBackground(java.awt.Color.black);
        borrartodo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        borrartodo.setForeground(new java.awt.Color(255, 102, 51));
        borrartodo.setText("🆑");
        borrartodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrartodoActionPerformed(evt);
            }
        });

        borrar.setBackground(java.awt.Color.black);
        borrar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        borrar.setForeground(new java.awt.Color(255, 102, 51));
        borrar.setText("C");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        entre.setBackground(java.awt.Color.black);
        entre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        entre.setForeground(new java.awt.Color(255, 102, 51));
        entre.setText("➗");
        entre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entreActionPerformed(evt);
            }
        });

        por.setBackground(java.awt.Color.black);
        por.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        por.setForeground(new java.awt.Color(255, 102, 51));
        por.setText("✖");
        por.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porActionPerformed(evt);
            }
        });

        menos.setBackground(java.awt.Color.black);
        menos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        menos.setForeground(new java.awt.Color(255, 102, 51));
        menos.setText("➖");
        menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosActionPerformed(evt);
            }
        });

        Raiz.setBackground(java.awt.Color.black);
        Raiz.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        Raiz.setForeground(new java.awt.Color(255, 102, 51));
        Raiz.setText("√ ");
        Raiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RaizActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        nine.setBackground(java.awt.SystemColor.activeCaptionText);
        nine.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        nine.setForeground(java.awt.Color.white);
        nine.setText("9");
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });

        eight.setBackground(java.awt.SystemColor.activeCaptionText);
        eight.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        eight.setForeground(java.awt.Color.white);
        eight.setText("8");
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });

        seven.setBackground(java.awt.SystemColor.activeCaptionText);
        seven.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        seven.setForeground(java.awt.Color.white);
        seven.setText("7");
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });

        five.setBackground(java.awt.Color.black);
        five.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        five.setForeground(java.awt.Color.white);
        five.setText("5");
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });

        four.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBox.darcula.backgroundColor1"));
        four.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        four.setForeground(java.awt.Color.white);
        four.setText("4");
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });

        two.setBackground(java.awt.Color.black);
        two.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        two.setForeground(java.awt.Color.white);
        two.setText("2");
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });

        six.setBackground(java.awt.Color.black);
        six.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        six.setForeground(java.awt.Color.white);
        six.setText("6");
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });

        zero.setBackground(java.awt.Color.black);
        zero.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        zero.setForeground(new java.awt.Color(245, 239, 239));
        zero.setText("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });

        punto.setBackground(java.awt.Color.black);
        punto.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 24)); // NOI18N
        punto.setForeground(new java.awt.Color(245, 239, 239));
        punto.setText(".");
        punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoActionPerformed(evt);
            }
        });

        three.setBackground(java.awt.Color.black);
        three.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        three.setForeground(java.awt.Color.white);
        three.setText("3");
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });

        one.setBackground(java.awt.Color.black);
        one.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        one.setForeground(java.awt.Color.white);
        one.setText("1");
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });

        igual.setBackground(new java.awt.Color(255, 102, 51));
        igual.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        igual.setForeground(new java.awt.Color(255, 102, 51));
        igual.setText("=");
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(four, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                            .addComponent(seven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(one, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .addComponent(igual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(punto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(punto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        mas.setBackground(java.awt.Color.black);
        mas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        mas.setForeground(new java.awt.Color(255, 102, 51));
        mas.setText("➕");
        mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masActionPerformed(evt);
            }
        });

        entrada.setEditable(false);
        entrada.setBackground(java.awt.Color.black);
        entrada.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        entrada.setForeground(java.awt.Color.white);
        entrada.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        entrada.setToolTipText("");
        entrada.setCaretColor(java.awt.Color.black);
        entrada.setDisabledTextColor(java.awt.Color.black);
        entrada.setSelectedTextColor(java.awt.Color.black);
        entrada.setSelectionColor(java.awt.Color.black);
        entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaActionPerformed(evt);
            }
        });

        porcentaje1.setBackground(java.awt.Color.black);
        porcentaje1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        porcentaje1.setForeground(new java.awt.Color(255, 102, 51));
        porcentaje1.setText("%");
        porcentaje1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porcentaje1ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("__________________________________");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Raiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(menos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(por, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(borrartodo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(porcentaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(entre, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(entrada, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrartodo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entre, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(porcentaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(por, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(mas, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(menos, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(Raiz, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entreActionPerformed
        // TODO add your handling code here:
        SELECIONARO("/");
    }//GEN-LAST:event_entreActionPerformed

    private void porActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porActionPerformed
        // TODO add your handling code here:
        SELECIONARO("*");
    }//GEN-LAST:event_porActionPerformed

    private void entradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_entradaActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        // TODO add your handling code here:
        entrada_datos("1");
    }//GEN-LAST:event_oneActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        // TODO add your handling code here:
        entrada_datos("2");
    }//GEN-LAST:event_twoActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        // TODO add your handling code here:
        entrada_datos("3");
    }//GEN-LAST:event_threeActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        // TODO add your handling code here:
        entrada_datos("0");
    }//GEN-LAST:event_zeroActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        // TODO add your handling code here:
        entrada_datos("4");
    }//GEN-LAST:event_fourActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        // TODO add your handling code here:
        entrada_datos("5");
    }//GEN-LAST:event_fiveActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        // TODO add your handling code here:
        entrada_datos("6");
    }//GEN-LAST:event_sixActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        // TODO add your handling code here:
        entrada_datos("7");
    }//GEN-LAST:event_sevenActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        // TODO add your handling code here:
        entrada_datos("8");
    }//GEN-LAST:event_eightActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        // TODO add your handling code here:
        entrada_datos("9");
    }//GEN-LAST:event_nineActionPerformed

    private void puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoActionPerformed
        // TODO add your handling code here:
        entrada_datos(".");
        

    }//GEN-LAST:event_puntoActionPerformed

    private void RaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RaizActionPerformed
        // TODO add your handling code here:
        
        n1= Double.parseDouble(entrada.getText());
        n1=Math.sqrt(n1);
        entrada.setText(sincero(n1));
        
    }//GEN-LAST:event_RaizActionPerformed

    private void masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masActionPerformed
        // TODO add your handling code here:
        
        
        SELECIONARO("+");
        
                
    }//GEN-LAST:event_masActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        // TODO add your handling code here:
        String Texto=entrada.getText().substring(0,entrada.getText().length()-1);
        entrada.setText(Texto);

    
        
    }//GEN-LAST:event_borrarActionPerformed

    private void borrartodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrartodoActionPerformed
        // TODO add your handling code here:
        entrada.setText("");
        n1=0;
        n2=0;
        operacion=" ";
       
        
    }//GEN-LAST:event_borrartodoActionPerformed

    private void menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosActionPerformed
        // TODO add your handling code here:
        SELECIONARO("-");
       
    }//GEN-LAST:event_menosActionPerformed

    private void porcentaje1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porcentaje1ActionPerformed
        // TODO add your handling code here:
        n1= Double.parseDouble(entrada.getText());
        n1=n1/100;
        entrada.setText(sincero(n1));
        
    }//GEN-LAST:event_porcentaje1ActionPerformed
   public String sincero(double resultado){
       
       String retorno = " ";
       retorno=Double.toString(resultado);
       
       if(resultado%1==0){
           retorno=retorno.substring(0,retorno.length()-2);
       }
       else {
           
       }
       return retorno;
   }
    
    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed
        // TODO add your handling code here:
        
        n2=Double.parseDouble(entrada.getText());
        
        switch(operacion){
            
            case "+":
            n2+=n1;
            entrada.setText(sincero(n2));
            break;
            case "-":
            n1-=n2;
            entrada.setText(sincero(n1));
            break;
            case "*":
            n2*=n1;
            
            entrada.setText(sincero(n2));
            break;
            case "/":
            n2/=n1;
            entrada.setText(sincero(n2));
            break;
            default :
                 entrada.setText(sincero(n1));
        }
    }//GEN-LAST:event_igualActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Raiz;
    private javax.swing.JButton borrar;
    private javax.swing.JButton borrartodo;
    private javax.swing.JButton eight;
    private javax.swing.JTextField entrada;
    private javax.swing.JButton entre;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JButton igual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton mas;
    private javax.swing.JButton menos;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JButton por;
    private javax.swing.JButton porcentaje1;
    private javax.swing.JButton punto;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
